import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Counter App',
  description: 'Generated by Counter App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full">
        <>{children}</>
      </body>
    </html>
  );
}
